const ActionTypes = {
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    PASSWORD_CHANGE: 'PASSWORD_CHANGE',
    SET_SERVER_MESSAGE: 'SET_SERVER_MESSAGE',
    CLEAR_SERVER_MESSAGE: 'CLEAR_SERVER_MESSAGE',
    HANDLE_CHANGE: 'HANDLE_CHANGE',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    LOG_OUT: 'LOG_OUT'
}
export default ActionTypes